-- MySQL Script generated by MySQL Workbench
-- 03/21/16 18:05:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema medical_master
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medical_master` ;

-- -----------------------------------------------------
-- Schema medical_master
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_master` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `medical_master` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(256) NULL,
  `authentication` VARCHAR(128) NULL,
  `type` INT NULL,
  `hosptialId` INT NULL,
  `nickName` VARCHAR(45) NULL,
  `createTime` DATETIME NULL,
  `sex` TINYINT(1) NULL,
  `department` VARCHAR(256) NULL,
  `educationLevel` INT NULL,
  `professionalRank` INT NULL,
  `title` VARCHAR(256) NULL,
  `identityNumber` VARCHAR(45) NULL,
  `doctorNumber` VARCHAR(45) NULL,
  `mobilePhoneNumber` VARCHAR(45) NULL,
  `status` INT NULL,
  `inviteCode` VARCHAR(45) NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`),
  INDEX `user_name` (`name` ASC),
  INDEX `phone_number` (`mobilePhoneNumber` ASC),
  INDEX `doctor_number` (`doctorNumber` ASC),
  INDEX `hospital` (`hosptialId` ASC),
  UNIQUE INDEX `inviteCode_UNIQUE` (`inviteCode` ASC));


-- -----------------------------------------------------
-- Table `workstation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workstation` ;

CREATE TABLE IF NOT EXISTS `workstation` (
  `workstationId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(256) NULL,
  `domains` VARCHAR(512) NULL,
  `keywords` VARCHAR(256) NULL,
  `allowDownload` TINYINT(1) NULL,
  `status` INT NULL,
  `createTime` DATETIME NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`workstationId`),
  INDEX `keywords` (`keywords` ASC),
  INDEX `name` (`name` ASC),
  INDEX `user` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagnostic_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagnostic_plan` ;

CREATE TABLE IF NOT EXISTS `diagnostic_plan` (
  `diagnosticPlanId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `category` INT NULL,
  `detail` VARCHAR(4096) NULL,
  `createTime` DATETIME NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userId` INT NULL,
  PRIMARY KEY (`diagnosticPlanId`),
  INDEX `name` (`name` ASC),
  INDEX `user` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system_property` ;

CREATE TABLE IF NOT EXISTS `system_property` (
  `propertyId` INT NOT NULL AUTO_INCREMENT,
  `categoryId` INT NOT NULL,
  `value` VARCHAR(128) NOT NULL,
  `comment` VARCHAR(256) NULL,
  `createTime` DATETIME NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`propertyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinical_research`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinical_research` ;

CREATE TABLE IF NOT EXISTS `clinical_research` (
  `clinicalResearchId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `applicationLocation` VARCHAR(512) NULL COMMENT 'id list separated by ,',
  `assignmentContractLocation` VARCHAR(512) NULL,
  `createTime` DATETIME NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userId` INT NULL,
  PRIMARY KEY (`clinicalResearchId`),
  INDEX `title` (`title` ASC),
  INDEX `user` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital` ;

CREATE TABLE IF NOT EXISTS `hospital` (
  `hospitalId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `level` INT NULL,
  `proviceId` INT NULL,
  `cityId` INT NULL,
  `districtId` INT NULL,
  `address` VARCHAR(256) NULL,
  PRIMARY KEY (`hospitalId`),
  INDEX `name` (`name` ASC),
  INDEX `address` (`address` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

CREATE TABLE IF NOT EXISTS `comment` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `commenterName` VARCHAR(45) NOT NULL,
  `contactInfo` VARCHAR(128) NULL,
  `commentTime` DATETIME NULL,
  `feedback` VARCHAR(45) NULL,
  `feedbackTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NULL,
  PRIMARY KEY (`commentId`),
  INDEX `user` (`userId` ASC),
  INDEX `name` (`commenterName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_material` ;

CREATE TABLE IF NOT EXISTS `training_material` (
  `materialId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `location` VARCHAR(1024) NULL,
  `createTime` DATETIME NULL,
  `lastUpdateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userId` INT NULL,
  PRIMARY KEY (`materialId`),
  INDEX `title` (`title` ASC),
  INDEX `user` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_property_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system_property_category` ;

CREATE TABLE IF NOT EXISTS `system_property_category` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
